# This is a workflow which display most of lowlighter/metrics features
#
# It is also used to detect broken plugins, so that's why "plugins_errors_fatal" is enabled on most of them,
# but you should set it to no if you're copying steps from this workflow
#
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (examples)
on:
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
#     - cron: "0 1-23/2 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'ramanverma2k/ramanverma2k'"
    steps:

      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================

      # Classic template example
      - name: 📗 Classic template
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes

      # ======================================================================================
      # 🧩 PLUGINS
      # ======================================================================================

      # ======================================================================================
      # ⏰ WakaTime plugin

      # Display your wakatime metrics
      - name: ⏰ WakaTime plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os

      # ======================================================================================
      # 📰 Recent activity

      # Display recent activity
      - name: 📰 Activity plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, star, push, repo

      # ======================================================================================
      # 💡 Coding habits

      # Display coding habits and recent activity (setup timezone for accurate metrics)
      - name: 💡 Habits plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata

      # ======================================================================================
      # 🈷️ Most used languages
      # 🈷️ Display most used languages (with some unwanted languages ignored, with details)
      - name: 🈷️ Languages plugin (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: kotlin, java
          plugin_languages_details: bytes-size, percentage
